name: Deploy Python Models

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi SSH ke VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Muat NVM/Node.js environment agar perintah 'pm2' dikenali oleh GitHub Actions
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/surauzamzam/models
            git pull origin main
            
            # 2. Gunakan python3.10 (hasil kompilasi kita) agar Flask 3.1.1 tidak error
            if [ ! -d "venv" ]; then
              python3.10 -m venv venv
            fi
            
            # 3. Install dependensi
            venv/bin/pip install -r requirements.txt
            
            # 4. Restart service Python di PM2
            pm2 restart models || pm2 start main.py --name models