name: Deploy Python Models

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi SSH ke VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/surauzamzam/models
            git pull origin main
            
            if [ ! -d "venv" ]; then
              python3.10 -m venv venv
            fi
            
            venv/bin/pip install -r requirements.txt
            
            if pm2 describe models-api > /dev/null; then
              pm2 restart models-api
            else
              pm2 start "venv/bin/gunicorn -w 4 -b 0.0.0.0:5000 app:app" --name models-api
            fi
            
            pm2 save